spring:
  application:
    name: habb-backend

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sankan
    username: root
    password: 123456

server:
  port: 8080

